### ISSUE TITLE
What's meaning of post_center_range?

### ISSUE THREAD

**Issue by MobiusLeo** [cnzzx/GeMap#13]
Hi, Thank you for answering my questions, I have a question that in config files, there is a parameter called post_center_range in bbox_coder fields. And it's been used as followed image:

![screenshot-20240725-105554](https://github.com/user-attachments/assets/045f6b9e-fbe4-4471-9a30-c370f35b03e9)
 What's the purpose of this?

**Comment by MobiusLeo** [comment]
![image](https://github.com/user-attachments/assets/15e707f5-4e7a-4eff-aaeb-8e577fb71d76)

**Comment by cnzzx** [comment]
Thanks for your interest. This param is in the form (x_min, y_min, x_min, y_min, x_max, y_max, x_max, y_max) and is used to filter out boxes out of the range. It's in fact not useful since the range is larger than the perception range. 
Moreover, the bboxes are computed with predicted polylines via (x_min, y_min, x_max, y_max).
