### ISSUE TITLE
error in multiscale_kernel_attn_forward_cuda: invalid configuration argument error in multiscale_kernel_attn_backward_cuda: invalid configuration argument

### ISSUE THREAD

**Issue by jasonchengf** [cnzzx/GeMap#4]
error in multiscale_kernel_attn_forward_cuda: invalid configuration argument
error in multiscale_kernel_attn_backward_cuda: invalid configuration argument
Hi, when I try to train my own data, the above error is reported, can I ask if you guys have encountered similar errors or have any recommended solution ideas?

**Comment by cnzzx** [comment]
Thanks for your interest. We haven't met this error, and it's hard to determine why it occurs without details. Generally, this error seems caused by Geometric Kernel Attention, which will project BEV points to image space and aggregate features. Since you're using your own data, there might be some problems in this process (image shape, projection matrix, etc.). Maybe you can check your data loading and parameters passed to the kernel. The [source code](https://github.com/cnzzx/GeMap/tree/master/projects/mmdet3d_plugin/gemap/modules/ops/geometric_kernel_attn/src) might also be helpful.

**Comment by jasonchengf** [comment]
Thanks for the advice you've provided, I've solved the problem so far, and I appreciate your help with it.
